### ISSUE TITLE
Event Donations

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/nosht#260]
I originally suggested a whole new model for fundraising/donation events, I know think that's more work and less user friendly.

I think a better way to do this would be to add another section to the existing events model to allow donations. This has the advantage that all existing features of events (email event updates to donors/attendees) are usable on fundraisers without any extra work.

So when you create an event, you can tick "ticket this event" and/or you can tick "take donations for this event".

Then on the event it'll have a very clear "Donate" button where the "Book" button is currently shown.

(In theory events can both sell tickets and take donations, in which case both buttons would show)

When you click "Donate" it'll load a modal (like the current "book" one) that asks you to:
1. sign-in with google or enter your email
2. enter the amount you wish to donate (and perhaps a message for the person/team raising money)
3. Ask if you'd like to use giftaid - same as the current form
4. make payment same - same as the current form

When creating or editing the event the host/fundraiser can decide whether they want to show how much they've raised and enter their target. If so the amount raised and a progress bar will be shown on the event for everyone to see.

I think this will take **4 days or 32 hours**.

---

Questions:
* does this approach make sense?
* by default the event start time and duration are required. Should we keep this required to make it optional? Slightly less work to keep it as is.
* am I missing any features?

**Comment by roselukas** [comment]
Love this idea. I think it makes complete sense. Queries to confirm:

1. So as a fundraiser coming to NOSHT, I would select 'take donations for this event' at the point of event creation? I might suggest we use the word 'fundraiser' where possible as that covers both event and non-event fundraiser. 
2. Will event/fundraiser organisers be able to suggest donation amounts, like different ticket types as well as have a separate box where guests/donors can choose donation amount? This is the ideal scenario
3. Currently we have a tick box for events checkouts, stating: “Yes, I would like to help the Hands Up Foundation to cover costs, by adding a 3% donation to my ticket price." Can we remove this for donations checkouts? 
4. I think we should make time and date optional please - can date be number of days as well as hours? Don't worry if too much. 
5. We may need to think a bit about wording on the events platform to indicate that people can hold their own fundraiser too. But that, I think is mainly for us.

**Comment by roselukas** [comment]
Hi Samuel

Really sorry to be so slow coming back on this one.

Yes please to differentiate between ‘donations’ and ‘tickets’.

Fine to play suggested donation/elective donation amount by ear.

Happy to come back to time/date issue.

Anything else you need from us to get going?

Thanks so much

Rose

**Comment by roselukas** [comment]
Hi Samuel

How are you? Just checking in on this one, we had discussed end of July – is that still feasible?

Thanks so much

Rose

From: Rose Lukas
Sent: 24 June 2020 12:16
To: samuelcolvin/nosht <reply@reply.github.com>; samuelcolvin/nosht <nosht@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [samuelcolvin/nosht] Event Donations (#260)

Hi Samuel

Really sorry to be so slow coming back on this one.

Yes please to differentiate between ‘donations’ and ‘tickets’.

Fine to play suggested donation/elective donation amount by ear.

Happy to come back to time/date issue.

Anything else you need from us to get going?

Thanks so much

Rose

**Comment by roselukas** [comment]
Samuel, 

It’s all working brilliantly. Donations etc… there’s nothing preventing key functionality, so I think we’re almost there. 

- One thing, do we need to ask for an email address when they’re making a donation, see screenshot 1? We do for buying tickets. [
![Screenshot 1](https://user-images.githubusercontent.com/41365539/88568468-f1164e80-d030-11ea-8118-c19f7ef097a3.png)
](url)

I have listed replacement text for the Guides when creating an event below. 
****

**REPLACEMENT GUIDANCE TEXT FOR CREATING AN EVENT IN ORDER** 

Public name of the fundraiser, keep this short and appealing. (required)

The Category of fundraiser you want to host. (required)

The type of fundraiser you want to host. (required)

Tick to make this fundraiser public so it will be visible to anyone on the site and appear in public search results. If your fundraiser is not public you will need to share the event link with people for them to view and book tickets or donate (depending on the event type).

Let guests know when the fundraiser will start and how long it will go on for, you can add more details about exact timings in the description below. If this event is for donations only, this date will be the deadline for donations. (required)

Drag the marker to set the exact fundraiser location – if no location is required, please leave this blank. (optional)

Maximum number of tickets/donations available for the fundraiser if applicable. (optional)

Price of standard tickets/donations for your fundraiser. Leave blank if tickets are free. You can add more ticket types/donation amounts once you've created the event. (optional)

Set if you're not selling tickets or asking for donations on a different platform e.g. Just Giving. (optional)

[under Long Description, greyed out text in box]: Full description of the fundraiser with everything your supporters need to know…

Detailed description of the fundraiser; you can update this later if you have more information. (required)

If it takes 2 mins to do, would any of the following be possible? If not, please leave!

-	Message box for donor, when making a donation (a bit like dietary requirements in the events ticket buyer box)
-	Title: Event Date or Fundraising deadline instead of Event Start when setting up event. (see screenshot 2) 
![Screenshot 2](https://user-images.githubusercontent.com/41365539/88568600-23c04700-d031-11ea-8a4c-3ebe3804b373.png)
- Upload a large image in place of the current map that appears on the final fundraiser page.

**Comment by samuelcolvin** [comment]
We already have email address, either they're already logged in or they have entered their email address on the first step of donating.

Try in an incognito window.

**Comment by roselukas** [comment]
Done. Great.

**Comment by samuelcolvin** [comment]
The text changes above look like you're renaming "events" to "fundraisers".  We can do that, but we should do it across the whole system, and that's a lot more work. Just changing it in one form is going to confuse people.

Perhaps ring me to discuss if you're not sure what I mean.

**Comment by roselukas** [comment]
Ok, can we put in the text “events/fundraisers” for all to get around that for now?

**Comment by samuelcolvin** [comment]
Personally I don't think the work "fundraiser" adds anything. All events for a charity (or technically for a company) that generate revenue are fundraisers.

I don't think most people who might casually host an event for Hands Up would understand the distinction I think you have:
* "fundraiser" means an event where people donate money "for nothing"
* "event" an event where people buy tickets in explicit return for the right to attend an event

I think the distinction "book tickets" vs. "donate" is much clearer both legally and practically for most people. It also works better for events that can allow both donations and ticket booking.

Of course if you really want "events/fundraisers" everywhere on the event creation page, I can stop being difficult and do it.

**Comment by roselukas** [comment]
I take your point - in which case Fundraiser for everything (covering ticket buying and non-ticket buying events) and we need to then change it across the site. There isn't time for that now, so perhaps we leave the guidance text with 'event' and hope no one notices or cares. Hopefully having added the extra 'ticket buying' / donation text will have covered it.

**Comment by samuelcolvin** [comment]
yes agree. Changing the text across the system is the kind of easy job that might be a good first job for someone else working on the project.

**Comment by roselukas** [comment]
Perfect
