### ISSUE TITLE
Rich Text for 'Send Update' Email

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#303]

**Comment by samuelcolvin** [comment]
The existing fairly simple WYSIWYG editor would be great for this - because it produces markdown it should work well with the existing email system.

The more complex HTML WYSIWYG suggested in #278 would mean plain text emails were very difficult and might require dynamic css for emails which would be difficult.

In short, whatever you do with #278 I would suggest using the editor currently used on events for this.

**Comment by roselukas** [comment]
Hi Nathan, can you update me on this and if I can send a simple update message to ticket holder? I need to include a link therefore a simple text editor would do for now.
