### ISSUE TITLE
Ticket type not found

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#315]
when clicking the donate button, the following error appears: 
![image](https://user-images.githubusercontent.com/41365539/96726277-b448c200-13a9-11eb-9f71-36e2bf3e1b75.png)

**Comment by roselukas** [comment]
This is only happening to this event: https://events.handsupfoundation.org/pvt/cinema-for-syria/cinema-for-syria-at-earls-court-film-festival-2020/

Please urgent if you can fix this.

**Comment by pro-Nate** [comment]
> This is only happening to this event: https://events.handsupfoundation.org/pvt/cinema-for-syria/cinema-for-syria-at-earls-court-film-festival-2020/
> 
I've investigated and found that this is caused by the event having an external ticket url.
When I remove the external ticket url, the donation button works properly.
It seems like the system expects the external url be used to donate if there is one - I don't know why this needs to be the case though.

**Comment by roselukas** [comment]
I removed the external link; you are completely right no need for it to be there. Thank you
